name: release
on:
  push:
    branches:
      - master
    tags:
      - v*
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Determine tags
        id: tags
        run: |
          echo -n ::set-output name=TAGS::
          IMAGE="quay.io/onecause/efs-provisioner"
          TAGS=('latest')
          if [[ "${GITHUB_REF}" =~ refs/tags/(v.*) ]]; then
            TAGS+=("${BASH_REMATCH[1]}")
          fi
          ( IFS=$','; echo "${TAGS[*]/#/$IMAGE:}" )
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ steps.tags.outputs.TAGS }}"